const express = require("express")
const mongoose = require("mongoose")
const router = require("./router/route")
const bodyParser = require("body-parser")
const multer = require("multer")
const app = express()
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))
app.use(multer().any())
mongoose.connect("mongodb+srv://abhinav7877:abhinavmangal@abhinav.yhc3th4.mongodb.net/backendapp?retryWrites=true&w=majority", { useNewUrlParser: true })
    .then(() => console.log("mongo Db conncted"))
    .catch(err => console.log(err))
app.use("/", router)
app.listen(process.env.port || 3000, function () {
    console.log("express run on this port" + (process.env.port || 3000))
})